services:
  postgres:
    image: postgres:16
    container_name: albion-db
    environment:
      POSTGRES_USER: albion
      POSTGRES_PASSWORD: Albion@123
      POSTGRES_DB: AlbionDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
